<?php
/**
 * @var $block \Magento\Cms\Api\Data\BlockInterface
 * @var $environmentStoreConfigViewModel \Overdose\Core\ViewModel\Adminhtml\EnvironmentStoreConfig
 * @var $secureRenderer \Magento\Framework\View\Helper\SecureHtmlRenderer
 */
$environmentStoreConfigViewModel = $block->getData('adminhtml_store_config_view_model');
$environmentBackgroundColour = $block->escapeHtmlAttr($environmentStoreConfigViewModel->getEnvironmentCssBackgroundColour());
$environmentTextColour = $block->escapeHtmlAttr($environmentStoreConfigViewModel->getEnvironmentCssTextColour());
?>

<?php if ($block->getChildHtml()) :?>
    <?php if ($environmentTextColour) :?>
        <?php $styleString = <<<style
                .page-main-actions .page-actions._fixed .page-actions-inner:before{color: $environmentTextColour;}
              style;?>
        <?= $secureRenderer->renderTag('style', [], $styleString, false);
    endif;?>

    <div data-mage-init='{"floatingHeader": {}}' class="page-actions floating-header"
        <?= /* @noEscape */ $environmentBackgroundColour ? ' style="background-color: ' . $environmentBackgroundColour .';"' : ''?>
        <?= /* @noEscape */ $block->getUiId('content-header') ?>>
        <?= $block->getChildHtml() ?>
    </div>
<?php endif; ?>
