<?php
/**
 * @var $block \Magento\Theme\Block\Html\Title
 * @var $environmentStoreConfigViewModel \Overdose\Core\ViewModel\Adminhtml\EnvironmentStoreConfig
 */
$titleIdHtml = ($block->getTitleId()) ? ' id="' . $block->escapeHtmlAttr($block->getTitleId()) . '"' : '';
$environmentStoreConfigViewModel = $block->getData('adminhtml_store_config_view_model');
$environmentTextColour = $block->escapeHtmlAttr($environmentStoreConfigViewModel->getEnvironmentCssTextColour());
$titleClass = ($block->getTitleClass()) ? ' ' . $block->getTitleClass() : '';
$title = $block->getPageTitle();
?>

<div class="page-title-wrapper<?= $block->escapeHtmlAttr($titleClass) ?>">
    <h1 class="page-title"<?= /* @noEscape */ $titleIdHtml ?><?= /* @noEscape */ $environmentTextColour ? ' style="color: ' . $environmentTextColour .';"' : ''?>><?= $block->escapeHtml($title) ?></h1>
    <?= $block->getChildHtml() ?>
</div>
